---
title: "Final Data Analysis"
author: "Hazel"
date: "12/7/2021"
output: html_document
---


```{r}
require(here)
```

```{r}
delomys = read.csv(here("data", "delomys.csv"))

delomys
```
```{r}
summary(delomys$body_mass)

summary(delomys$body_length)
```

```{r}
shapiro.test(delomys$body_mass)
```
```{r}
shapiro.test(delomys$body_length)
```
```{r}
plot(x = delomys$body_mass, y = delomys$body_length, main = "Delomys Body Length and Body Mass", xlab = "Body Length", ylab = "Body Mass")

```
```{r}
hist(delomys$body_mass, main = "Delomys Body Mass", xlab = "Body Mass", breaks = 10)

```
```{r}
hist(delomys$body_length, main = "Delomys Body Length", xlab = "Body Length")

```
```{r}
boxplot(body_mass ~ binomial, data = delomys, xlab = "Species", ylab = "Body Mass")
```
```{r}
boxplot(body_mass ~ sex, data = delomys, xlab = "Sex", ylab = "Body Mass")
```

```{r}
boxplot(body_mass ~ sex + binomial, data = delomys, xlab = "Species by Sex", ylab = "Body Mass")


```
fit_1 = lm(p.cut ~ rope.type, data=rope)
anova(fit_1)
anova_fit_1 = anova(fit_1)

```{r}
# Model 1: simple linear regression

fit1 = lm(delomys$body_length ~ delomys$body_mass, data = delomys)

lm(fit1)

model1 = lm(fit1)

```
```{r}

residuals(fit1)
```

```{r}
# Model 2: 1-way ANOVA 

fit2 = lm(delomys$body_mass ~ delomys$sex, data = delomys)

fit2

anova(fit2)

model2 = anova(fit2)
```
```{r}
residuals(fit2)
```

```{r}
# Model 3: 1-way ANOVA 

fit3 = lm(delomys$body_mass ~ delomys$binomial, data = delomys)

fit3

anova(fit3)

model3 = anova(fit3)
```

```{r}
residuals(fit3)
```


```{r}
# Model 4: 2-way additive ANOVA 

fit4 = lm(delomys$body_mass ~ delomys$sex + delomys$binomial, data = delomys)

fit4

anova(fit4)

model4 = anova(fit4)
```
```{r}
residuals(fit4)
```


```{r}
# Model 5: 2-way factorial ANOVA 

fit5 = lm(delomys$body_mass ~ delomys$sex * delomys$binomial, data = delomys)

fit5

anova(fit5)

model5 = anova(fit5)
```

```{r}
residuals(fit5)
```

```{r}
hist(residuals(fit1), main = "Model Residuals for Fit1", xlab = "Fit1 Residuals")
```


```{r}
hist(residuals(fit2), main = "Model Residuals for Fit2", xlab = "Fit2 Residuals")
```

```{r}
hist(residuals(fit3), main = "Model Residuals for Fit3", xlab = "Fit3 Residuals")
```
```{r}
hist(residuals(fit4), main = "Model Residuals for Fit4", xlab = "Fit4 Residuals")
```
```{r}
hist(residuals(fit5), main = "Model Residuals for Fit5", xlab = "Fit5 Residuals")
```
```{r}
shapiro.test(residuals(fit1))
shapiro.test(residuals(fit2))
shapiro.test(residuals(fit3))
shapiro.test(residuals(fit4))
shapiro.test(residuals(fit5))
```

```{r}
summary(fit1)
summary(fit2)
summary(fit3)
summary(fit4)
summary(fit5)

```

```{r}
knitr::kable(coef(summary(fit1)))
knitr::kable(coef(summary(fit2)))
knitr::kable(coef(summary(fit3)))
knitr::kable(coef(summary(fit4)))
knitr::kable(coef(summary(fit5)))
```

```{r}

knitr::kable(anova(fit1))
knitr::kable(anova(fit2))
knitr::kable(anova(fit3))
knitr::kable(anova(fit4))
knitr::kable(anova(fit5))

```

```{r}
AIC(fit2)
AIC(fit3)
AIC(fit4)
AIC(fit5)
```

